#!/usr/bin/env bash
# ============================================================
# DESPLIEGUE EN RENDER — Script de configuración
# ============================================================
# Este script configura el servicio en Render usando la CLI
# de Render (si está disponible) o genera las instrucciones
# para hacerlo manualmente desde el dashboard.
# ============================================================

echo "============================================================"
echo "  DESPLIEGUE EN RENDER — TecnoGamer"
echo "============================================================"
echo ""
echo "1. Ve a https://render.com/"
echo "2. Inicia sesión con GitHub"
echo "3. Click en 'New' → 'Web Service'"
echo "4. Conecta el repositorio: github.com/foxnismone/tg-store-2026"
echo "5. Configura:"
echo "   - Name: tecnogamer"
echo "   - Environment: Node"
echo "   - Build Command: npm install --ignore-scripts"
echo "   - Start Command: node backend/server.js"
echo "   - Instance Type: Free"
echo "6. Variables de entorno (ya están en render.yaml):"
echo "   - NODE_ENV=production"
echo "   - PORT=10000"
echo "   - JWT_SECRET (generar automáticamente)"
echo "   - DB_PATH=/data/tecnogamer.db"
echo "   - UPLOAD_DIR=/data/uploads"
echo "   - BACKUP_DIR=/data/backups"
echo "   - SITE_URL=https://tecnogamer.onrender.com"
echo "   - SITE_NAME=TecnoGamer"
echo "   - CORS_ORIGIN=https://tecnogamer.onrender.com"
echo "7. Click en 'Create Web Service'"
echo ""
echo "Render desplegará automáticamente y te dará una URL"
echo "como https://tecnogamer.onrender.com"
echo ""
echo "============================================================"
echo "  NOTAS IMPORTANTES"
echo "============================================================"
echo ""
echo "• El tier gratuito tiene cold start de 30-60 segundos"
echo "  tras 15 minutos de inactividad."
echo ""
echo "• La base de datos SQLite se almacenará en /data/"
echo "  que es un volumen persistente en Render."
echo ""
echo "• Las imágenes de productos están en uploads/products/"
echo "  y se sirven estáticamente."
echo ""
echo "• El panel de operador estará en /admin.html"
echo ""
echo "• Credenciales por defecto:"
echo "   Email: admin@tecnogamer.local"
echo "   Password: Admin123!"
echo ""
echo "⚠️  CAMBIA LA CONTRASEÑA DEL ADMIN INMEDIATAMENTE"
echo ""
echo "============================================================"
